### ISSUE TITLE
crashes on startup with "panic"

### ISSUE THREAD

**Issue by mhellwig** [slashformotion/radioboat#5]
Installed on ARCH via AUR, so dependencies should be okay. urls.csv contains one station for testing. starting up leads to:

```
$ radioboat
panic: dial unix /tmp/BpLnfgDsc2WD: connect: no such file or directory

goroutine 1 [running]:
github.com/blang/mpv.(*IPCClient).run(0xc000079fb0)
        github.com/blang/mpv@v0.0.0-20160810175505-d56d7352e068/ipc.go:83 +0x165
github.com/blang/mpv.NewIPCClient(...)
        github.com/blang/mpv@v0.0.0-20160810175505-d56d7352e068/ipc.go:60
github.com/slashformotion/radioboat/internal/players.(*MpvPlayer).Init(0xc0002141c0)
        github.com/slashformotion/radioboat/internal/players/mpv.go:33 +0x23d
github.com/slashformotion/radioboat/internal/tui.InitialModel({_, _}, {_, _, _}, _)
        github.com/slashformotion/radioboat/internal/tui/tui.go:116 +0x1cc
github.com/slashformotion/radioboat/cmd.ui()
        github.com/slashformotion/radioboat/cmd/root.go:52 +0xa7
github.com/slashformotion/radioboat/cmd.glob..func2(0x55947b47a120?, {0x55947b202f07?, 0x0?, 0x0?})
        github.com/slashformotion/radioboat/cmd/root.go:24 +0x17
github.com/spf13/cobra.(*Command).execute(0x55947b47a120, {0xc000012200, 0x0, 0x0})
        github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x55947b47a120)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
github.com/slashformotion/radioboat/cmd.Execute()
        github.com/slashformotion/radioboat/cmd/root.go:39 +0xeb
main.main()
        github.com/slashformotion/radioboat/main.go:9 +0x17
```

**Comment by slashformotion** [comment]
The master branch is patched, I need to release is on the AUR. I will do it today.

**Comment by slashformotion** [comment]
@mhellwig  This is now fixed you can update the AUR package to it's newest version `v0.1.2`
